/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyCanvas */

#ifndef _Included_MyCanvas
#define _Included_MyCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef MyCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define MyCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef MyCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define MyCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef MyCanvas_FOCUS_TRAVERSABLE_SET
#define MyCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef MyCanvas_TOP_ALIGNMENT
#define MyCanvas_TOP_ALIGNMENT 0.0f
#undef MyCanvas_CENTER_ALIGNMENT
#define MyCanvas_CENTER_ALIGNMENT 0.5f
#undef MyCanvas_BOTTOM_ALIGNMENT
#define MyCanvas_BOTTOM_ALIGNMENT 1.0f
#undef MyCanvas_LEFT_ALIGNMENT
#define MyCanvas_LEFT_ALIGNMENT 0.0f
#undef MyCanvas_RIGHT_ALIGNMENT
#define MyCanvas_RIGHT_ALIGNMENT 1.0f
#undef MyCanvas_serialVersionUID
#define MyCanvas_serialVersionUID -7644114512714619750i64
#undef MyCanvas_serialVersionUID
#define MyCanvas_serialVersionUID -2284879212465893870i64
/*
 * Class:     MyCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_MyCanvas_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
